[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - 410323 - LOGS_CAPTURED - Started capturing logs in process (pid: 410323).
[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - 410323 - bike_rental_features - STEP_START - Started execution of step "bike_rental_features".
[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - bike_rental_features - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/daily_bike_rental_demand using PickledObjectFilesystemIOManager...
[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - 410323 - bike_rental_features - LOADED_INPUT - Loaded input "daily_bike_rental_demand" using input manager "io_manager"
[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - 410323 - bike_rental_features - STEP_INPUT - Got input "daily_bike_rental_demand" of type "DataFrame". (Type check passed).
[32m2024-12-10 16:04:18 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 5e545b85-f69e-426b-936f-a1d1d9a10aa5 - 410323 - bike_rental_features - STEP_FAILURE - Execution of step "bike_rental_features" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "bike_rental_features"::

KeyError: "['cnt_lag_1', 'cnt_lag_2', 'cnt_lag_3', 'cnt_lag_4', 'cnt_lag_5', 'cnt_lag_6'] not in index"

Stack Trace:
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 490, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/kai/Git/twai_mlops_assignment2-main/src/bike_share/assets/bike_rental_features.py", line 17, in bike_rental_features
    return daily_bike_rental_demand[columns]
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
[0m
