[32m2024-12-11 15:11:53 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - LOGS_CAPTURED - Started capturing logs in process (pid: 629479).
[32m2024-12-11 15:11:53 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - STEP_START - Started execution of step "linear_regression".
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - linear_regression - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/test_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - LOADED_INPUT - Loaded input "test_data" using input manager "io_manager", from output "test_data" of step "train_test_data"
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - linear_regression - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/train_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - LOADED_INPUT - Loaded input "train_data" using input manager "io_manager", from output "train_data" of step "train_test_data"
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - STEP_INPUT - Got input "test_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - STEP_INPUT - Got input "train_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:11:54 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - c443b218-0f04-48cf-9151-f108f218e676 - 629479 - linear_regression - STEP_FAILURE - Execution of step "linear_regression" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "linear_regression"::

ValueError: Found input variables with inconsistent numbers of samples: [1090, 1096]

Stack Trace:
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 490, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/kai/Git/twai_mlops_assignment2-main/src/bike_share/assets/models.py", line 59, in linear_regression
    create_pipeline(LinearRegression()).fit(train_input, train_output)
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/linear_model/_base.py", line 609, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1320, in check_X_y
    check_consistent_length(X, y)
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/sklearn/utils/validation.py", line 457, in check_consistent_length
    raise ValueError(
[0m
